### ISSUE TITLE
Some confusion

### ISSUE THREAD

**Issue by tools-only** [tanimutomo/gcmc#21]
Hi there, it is really a light coding. But when I tried it on Google Colab（python3, torch==1.1.0）, I got this:  
` 'RGCLayer' object has no attribute 'update_args' `
It seems like sth is wrong with the inheritance of class 'MessagePassing', have you ever encountered this?

**Comment by tanimutomo** [comment]
@tools-only 
Sorry for very late to respond to this issue...
I updated the master branch and changed the requirements.txt to specify the versions for all required packages.
Please check the latest code.
