### ISSUE TITLE
 'RGCLayer' object has no attribute 'message_args'

### ISSUE THREAD

**Issue by GalaxyCruiser** [tanimutomo/gcmc#22]
when I running the main.py without docker, the error occur as follows:
```bash
(py36) iip@iip:~/gcmc$ python main.py
Downloading http://files.grouplens.org/datasets/movielens/ml-100k.zip
Extracting data/ml-100k/ml-100k.zip
Processing...
Done!
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main(config)
  File "main.py", line 40, in main
    trainer.iterate()
  File "/home/iip/gcmc/src/train.py", line 28, in iterate
    loss, train_rmse = self.train(epoch)
  File "/home/iip/gcmc/src/train.py", line 47, in train
    self.data.edge_type, self.data.edge_norm
  File "/home/iip/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/iip/gcmc/src/model.py", line 14, in forward
    u_features, i_features = self.gcenc(x, edge_index, edge_type, edge_norm)
  File "/home/iip/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/iip/gcmc/src/model.py", line 32, in forward
    features = self.rgc_layer(x, edge_index, edge_type, edge_norm)
  File "/home/iip/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/iip/gcmc/src/layers.py", line 54, in forward
    return self.propagate(self.accum, edge_index, x=x, edge_type=edge_type, edge_norm=edge_norm)
  File "/home/iip/gcmc/src/layers.py", line 67, in propagate
    for arg in self.message_args:
  File "/home/iip/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'RGCLayer' object has no attribute 'message_args'
```
the environment is:
Ubuntu 18.04.2 LTS
CUDA 10.0
pytorch 1.2
python 3.6

**Comment by zdchu** [comment]
Same error as you, do you have any solution?

**Comment by GalaxyCruiser** [comment]
> Same error as you, do you have any solution?

No， and I tried Docker too, still failed. The author seems abandoned the repo.

**Comment by zdchu** [comment]
> 
> 
> > Same error as you, do you have any solution?
> 
> No， and I tried Docker too, still failed. The author seems abandoned the repo.

I fixed it by change self.message_args to self.__message_args__, self.update_args as the same.

**Comment by tanimutomo** [comment]
Sorry for very late to respond to this issue..., And thanks to sharing your solution @zdchu .
I merged the #24 to the master branch.
In this pull request, I specified the versions for the all required libraries for avoiding incompatibility errors like this issue.
Please check the latest code and `README.md`

Thanks.

**Comment by Slam1423** [comment]
> 
> 
> > > Same error as you, do you have any solution?
> > 
> > 
> > No， and I tried Docker too, still failed. The author seems abandoned the repo.
> 
> I fixed it by change self.message_args to self.**message_args**, self.update_args as the same.

Sorry, how you fixed this problem? What's the meaning of changing self.message_args to self.**message_args** ?

**Comment by Slam1423** [comment]
> 
> 
> > > > Same error as you, do you have any solution?
> > > 
> > > 
> > > No， and I tried Docker too, still failed. The author seems abandoned the repo.
> > 
> > 
> > I fixed it by change self.message_args to self.**message_args**, self.update_args as the same.
> 
> Sorry, how you fixed this problem? What's the meaning of changing self.message_args to self.**message_args** ?

@zdchu

**Comment by Karthikeyan-Ram** [comment]
Is that we need to change ----> self.message_args to self.update_args ?

**Comment by Karthikeyan-Ram** [comment]
Request help to fix this issue
