### ISSUE TITLE
Torch API change: Error occurs when build/run the docker

### ISSUE THREAD

**Issue by xuetf** [tanimutomo/gcmc#23]
I first run the command of cpu version in the README:
1. error occur when build the docker:
ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.0.0 which is incompatible.
Then,
2. I change the torch version from 1.0.0 to 1.3.1 in cpu_requirements.txt
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from src.dataset import MCDataset
  File "/app/src/dataset.py", line 11, in <module>
    from torch_geometric.utils import one_hot
ImportError: cannot import name 'one_hot'

I guess it's due to the change of the API in torch_geometric.

**Comment by tanimutomo** [comment]
Thanks for watching my repository and reporting the bugs for dependencies.
Sorry, I was late to respond to this issue.

The cause of this error is attributed to torchvision version.
This repo's code doesn't support the pytorch and pytorch geometric latest version, also torchvisino too.
So, I specified the version to the all required libraries for avoiding the errors related to the libraries' version.
Please pull the latest version of this repo and try again in a virtual environment!
Please see the `README.md` for more details about creating the environment.

Thanks.
